export {SharedCustomerLayout} from "../layout/sharedCustomerLayout/sharedCustomerLayout";
export {SharedManagmentLayout} from "../layout/sharedManagmentLayout/sharedManagmentLayout";
export {Home} from "./home/home";
export {Category} from "./home/category";
export {Product} from "./home/product";
export {Cart} from "./home/cart";
export {FinalizePayment} from "./paymant/finalizePayment";
export {PaymentGateWay} from "./paymant/paymentGateWay";
export {ResultOfPayment} from "./paymant/resultOfPayment";
export {Cancelation} from "./paymant/cancelation";
export {Login} from "./login/login";
export {Order} from "./managment/order";
export {InventoryPrices} from "./managment/inventoryPrices";
export {Goods} from "./managment/goods";
export {Error} from "./error/error"